name: kh_ooi
channels:
  - conda-forge
  - defaults
dependencies:
# from OOI 
  - python=3.10
  - argcomplete
  - beautifulsoup4
  - bottleneck
  - cgsn_parsers
  - chest
  - conda-build
  - configobj
  - dask
  - erddapy
  - geos
  - gsw
  - hdf4
  - h5netcdf
  - ioos_qc
  - jupyterlab
  - libnetcdf
  - matplotlib
  - munch>=2.1.0
  - netcdf4
  - nodejs
  - nose
  - numexpr
  - numpy
  - pip
  - pocean-core
  - pyasn1
  - pyaxiom
  - pygc
  - pyIGRF
  - pyncml
  - pytz
  - pysolar
  - pyYAML
  - scipy
  - simplejson
  - sockjs-tornado
  - tqdm
  - xarray
  - xlrd
  - yaml
  - pip:
    - https://bitbucket.org/ooicgsn/pyseas/get/develop.zip
    - https://bitbucket.org/ooicgsn/cgsn-processing/get/master.zip
  # addons from loenv.yml 
  # from Rob Hetland 
  - cf_xarray
  - cartopy
  - cmocean
  - dask-labextension
  - datashader
  - geoviews
  - holoviews
  - hvplot
  - jupyter
  - numba >= 0.49
  - openpyxl
  - xgcm
  - zarr
  # from Parker MacCready 
  - UTide
  - ephem
  - git 
  - lxml
  - seawater
  - sqlalchemy
  - pip:
    - -e ../../../LO/lo_tools/ lo_tools # package of local modules 
    - azure-storage-blob
    - PyCO2SYS
  # from Parker MacCready non-python tools
  - ffmpeg
  # my additions
  - nco #  have to install homebrew and nco before this one


  

